export default {
  "Gym": 0,
  "Liquid": 0,
  "Lemon water": 0,
  "Tea(black/green)": 0,
  "Fruit tea": 0,
  "Water": 0,
  "Latte": 0,
  "Mineral water (Esentuki - 4)": 0,
  "Mineral water (Borjomi)": 0,
  "Mineral water (Prolom)": 0,
  "Tequila": 0,
  "Red wine": 0,
  "White wine": 0,
  "Strong alcohol": 0,
  "Beer": 0,
  "Morse": 0,
  "Milk": 0,
  "Orange juice": 0,
  "Oatmeal": 0,
  "Pizza with meat": 0,
  "Cheese Pizza": 0,
  "Cheesecakes": 0,
  "Scrambled eggs": 0,
  "Mayonnaise salad": 0,
  "Bread": 0,
  "Meat": 0,
  "Sauce": 0,
  "Cutlet": 0,
  "Sausage": 0,
  "Fish": 0,
  "Sushi": 0,
  "Cod liver": 0,
  "Cheese": 0,
  "Curd": 0,
  "Sour cream": 0,
  "Buckwheat porridge": 0,
  "Noodles with vegetables": 0,
  "Noodles with shrimp": 0,
  "Meat pilaf": 0,
  "Meatless pilaf": 0,
  "Pea soup with meat": 0,
  "Fried vegetables": 0,
  "Pyagse with vegetables": 0,
  "Dumplings with cabbage": 0,
  "Potato dumplings": 0,
  "Zucchini Fritters": 0,
  "Stewed cabbage": 0,
  "Solyanka with meat": 0,
  "Eggplant with cheese": 0,
  "Pasta": 0,
  "Fried potatoes": 0,
  "Cooked Potatoes": 0,
  "Braised Potatoes": 0,
  "Mashed potatoes": 0,
  "Apple Pie": 0,
  "Patty with cabbage": 0,
  "Curd Pie": 0,
  "Cheese Pie": 0,
  "Egg Pie": 0,
  "Potato pie": 0,
  "Meat pie": 0,
  "Khachapuri": 0,
  "The nuts": 0,
  "Pumpkin seeds": 0,
  "Raisins": 0,
  "Dried apricots": 0,
  "Vegetable salad": 0,
  "Eggplant caviar": 0,
  "The vinaigrette": 0,
  "Peach": 0,
  "Melon": 0,
  "Plum": 0,
  "Tangerines": 0,
  "Pear": 0,
  "Watermelon": 0,
  "Banana": 0,
  "Grapes": 0,
  "Pineapple": 0,
  "Orange": 0,
  "Paste": 0,
  "Kumquat": 0,
  "Ice cream": 0,
  "Cookie": 0,
  "Cake": 0,
  "Bun": 0,
  "Croissant": 0,
  "Chocolate": 0,
  "Candies": 0,
  "Halva": 0,
  "Marshmallow": 0,
  "Red caviar": 0,
  "Jelly": 0
}
